In [1]:
import pandas as pd
import numpy as np

In [110]:
data = {
    "Product": ["Laptop", "Mouse", "Keyboard"],
    "Price": [80000, 500, 1500],
    "Stock": [10, 50, 30]
}

In [111]:
df=pd.DataFrame(data)
df

    Product  Price  Stock
0    Laptop  80000     10
1     Mouse    500     50
2  Keyboard   1500     30

In [112]:
#Q2
df["Price"]
df[["Price", "Stock"]]

   Price  Stock
0  80000     10
1    500     50
2   1500     30

In [113]:
#Q3
df["Discount"]=[10,5,8]
df

    Product  Price  Stock  Discount
0    Laptop  80000     10        10
1     Mouse    500     50         5
2  Keyboard   1500     30         8

In [114]:
#Q4
df.drop("Stock",axis=1,inplace=True)
df

    Product  Price  Discount
0    Laptop  80000        10
1     Mouse    500         5
2  Keyboard   1500         8

In [115]:
#Q5
df.drop(1,axis=0,inplace=True)
df

    Product  Price  Discount
0    Laptop  80000        10
2  Keyboard   1500         8

In [116]:
#Q6
df.loc[0]
df.loc[[0,2]]#how can I have first and third rows together when only two rows will be remaining?

    Product  Price  Discount
0    Laptop  80000        10
2  Keyboard   1500         8

In [117]:
#Q7
df.loc[[0,2]][["Product","Price"]]
df.loc[0]

Product     Laptop
Price        80000
Discount        10
Name: 0, dtype: object

In [2]:
#Q8
'''
in df.drop("Price", axis=1), the "Price" column is delted temporarily where as
in df.drop("Price", axis=1, inplace=True) "Price" column is deleted permanently
'''

'\nin df.drop("Price", axis=1), the "Price" column is delted temporarily where as\nin df.drop("Price", axis=1, inplace=True) "Price" column is deleted permanently\n'

In [3]:
#nan=not a number(i.e; null value)
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [4]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [5]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [6]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [7]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [9]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0