In [2]:
import numpy as np
import pandas as pd

In [3]:
k = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df=pd.DataFrame(k)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [4]:
df[df["Age"]>30]["City"]

1     Paris
3    London
Name: City, dtype: object

In [5]:
p={
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
p=pd.DataFrame(p)
p

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [6]:
p.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [8]:
nafillervalues={'A':123,'B':456,'C':789,'D':101112}
p.fillna(value=nafillervalues)

       A  B      C         D
0    1.0  1    1.0       1.0
1    2.0  2    2.0  101112.0
2  123.0  3    3.0  101112.0
3    4.0  4  789.0  101112.0
4    5.0  5  789.0       5.0