In [83]:
import numpy as np
import pandas as pd

In [84]:
#Dataframes are multi dimension series

In [85]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

In [86]:
df = pd.DataFrame(data)#or just type pd.DataFrame(data) and you'll still get the output on the notebook  
print(df)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [87]:
data = [
    ["Aryan",18],
    ["Anjali",14],
    ["Angad",15]
]
pd.DataFrame(data)

        0   1
0   Aryan  18
1  Anjali  14
2   Angad  15

In [88]:
column=["Name","age"]
pd.DataFrame(data,columns=column)

     Name  age
0   Aryan   18
1  Anjali   14
2   Angad   15

In [89]:
df2 = pd.DataFrame(data,columns=column)
df2["Name"] #will only select Name column

0     Aryan
1    Anjali
2     Angad
Name: Name, dtype: object

In [90]:
df2[["Name","age"]]#to show multiple columns at once, you'll have to put in a list of columns

     Name  age
0   Aryan   18
1  Anjali   14
2   Angad   15

In [91]:
df2["Dream"]=["AIML Engineer", "Stock Broker", "Boxer"]
df2["Gender"]=["M","F","M"]
df2

     Name  age          Dream Gender
0   Aryan   18  AIML Engineer      M
1  Anjali   14   Stock Broker      F
2   Angad   15          Boxer      M

Now to remove a column, Let's Say: the 'age' column:-

In [92]:
df2.drop("age",axis=1)

     Name          Dream Gender
0   Aryan  AIML Engineer      M
1  Anjali   Stock Broker      F
2   Angad          Boxer      M

In [93]:
df2

     Name  age          Dream Gender
0   Aryan   18  AIML Engineer      M
1  Anjali   14   Stock Broker      F
2   Angad   15          Boxer      M

Notice how it doesn't permanently deletes the "age" column? to do that...

In [94]:
df2.drop("age",axis=1,inplace=True)
df2

     Name          Dream Gender
0   Aryan  AIML Engineer      M
1  Anjali   Stock Broker      F
2   Angad          Boxer      M

To delete multiple columns...

In [95]:
df2.drop(["Gender","Dream"],axis=1)#not using implace = True because I didn't wanted to mess up the table

     Name
0   Aryan
1  Anjali
2   Angad

In [96]:
df2

     Name          Dream Gender
0   Aryan  AIML Engineer      M
1  Anjali   Stock Broker      F
2   Angad          Boxer      M

To delete a row..

In [99]:
df2.drop(0,axis=0)#not required to type axis=0 as it is by default(note: it's not permanently deleted yet unless you type: inplace=True)

     Name         Dream Gender
1  Anjali  Stock Broker      F
2   Angad         Boxer      M

Now to access a row....

In [100]:
df2.loc[0]#first element say

Name              Aryan
Dream     AIML Engineer
Gender                M
Name: 0, dtype: object

To access multiple row...

In [101]:
df2.loc[[0,1]]

     Name          Dream Gender
0   Aryan  AIML Engineer      M
1  Anjali   Stock Broker      F