In [2]:
import numpy as np 
import pandas as pd

In [3]:
#nan=not a number(i.e; null value)
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [4]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

Finding missing Data

In [5]:
#to find if a column has a nan value
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [6]:
#to find the number of nan values of rows:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [ ]:
#to check if every column contains nan value or not
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

Removing any NaN data row

In [8]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
#to print rows which has n number of NON-NULL values
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [10]:
df.dropna(thresh=4)

     A  B    C    D
0  1.0  1  1.0  1.0

In [11]:
df.dropna(thresh=5)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

Filling the missing data

In [12]:
#to fill all the nan values with same number:-
df.fillna(25)

      A  B     C     D
0   1.0  1   1.0   1.0
1   2.0  2   2.0  25.0
2  25.0  3   3.0  25.0
3   4.0  4  25.0  25.0
4   5.0  5  25.0   5.0

But what if I want to fill a specific number for nan value for a specific column?

In [13]:
fillnavalues = {'A':0,'B':25,'C':100,'D':1000}
df.fillna(value=fillnavalues)

     A  B      C       D
0  1.0  1    1.0     1.0
1  2.0  2    2.0  1000.0
2  0.0  3    3.0  1000.0
3  4.0  4  100.0  1000.0
4  5.0  5  100.0     5.0