In [28]:
import numpy as np
import pandas as pd

In [29]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [30]:
df1.shape

(5, 3)

In [31]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [32]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [33]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [34]:
df1["A"]+100

0    101
1    102
2    103
3    104
4    105
Name: A, dtype: int64

Suppose now I want to find the cube of B columns elements by making and calling in that function, then...

In [35]:
def cuber(x):
    return x**3

In [25]:
df1["B"].apply(cuber)

0      1000
1      8000
2     27000
3     64000
4    125000
Name: B, dtype: int64

But now I want to apply the changes in the actual table so...

In [37]:
df1["B"]= df1["B"].apply(cuber)
df1

   A       B    C       D
0  1    1000  100    1000
1  2    8000  200    8000
2  3   27000  300   27000
3  4   64000  400   64000
4  5  125000  500  125000

In [38]:
df1["D"]= df1["B"].apply(cuber)
df1

   A       B    C                 D
0  1    1000  100        1000000000
1  2    8000  200      512000000000
2  3   27000  300    19683000000000
3  4   64000  400   262144000000000
4  5  125000  500  1953125000000000