In [1]:
import numpy as np
import pandas as pd

In [13]:
#series = 1D list which can store multiple data type
#labels = indexes
labels=['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={"one":10,"two":20,"three":30}

In [3]:
pd.Series(my_list)#will print all the values of list 'my_list' alongside indexes

0    10
1    20
2    30
dtype: int64

In [4]:
pd.Series(my_list,index=labels)
#will print all the values of list 'my_list' with indexes being a,b and c

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(arr)

10    10
20    20
30    30
dtype: int64

In [14]:
pd.Series(d)

one      10
two      20
three    30
dtype: int64